# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: sig-service-prod
  labels:
    app: sig-service-prod
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: sig-service-prod
  type: ClusterIP
