# Kubernetes
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sig-service-prod-v0
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sig-service-prod
        version: v0
    spec:
      containers:
      - name: rdr2tls
        image: dysinger/rdr2tls:0.1.1
        command:
        - rdr2tls
        - --port
        - "8080"
        ports:
        - name: http
          containerPort: 8080
      - name: sig-service
        image: commercialhaskell/sig-service:prod
        imagePullPolicy: Always
        command:
        - sig-service
        - Testing
        - --port
        - "8443"
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: secret
          mountPath: /opt/sig-service/secret
      volumes:
      - name: secret
        secret:
          secretName: sig-service-prod
