# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: sig-service
  labels:
    app: sig-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: sig-service
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sig-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sig-service
    spec:
      containers:
      - name: rdr2tls
        image: dysinger/rdr2tls:0.1.1
        command:
        - rdr2tls
        - --port
        - "8080"
        ports:
        - name: http
          containerPort: 8080
        restartStrategy: always
      - name: sig-service
        image: dysinger/sig-service:0.0.1
        command:
        - sig-service
        - Testing
        - --port
        - "8443"
        ports:
        - name: https
          containerPort: 8443
        restartStrategy: always
        volumeMounts:
        - name: secret
          mountPath: /opt/sig-service/secret
      volumes:
      - name: secret
        secret:
          secretName: sig-service
---
apiVersion: v1
kind: Secret
metadata:
  name: sig-service
type: Opaque
data:
  github.pem: |
    << base64 encoded github private ssh key goes here >>
