apiVersion: v1
kind: ReplicationController
metadata:
  name: consul-vault-0-0-1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: consul-vault
        ver: 0.0.1
    spec:
      containers:
      - name: consul
        image: dysinger/consul:0.5.2
        env:
          - name: CONSUL_ACL_MASTER_TOKEN
            value: bba227cc-6ef8-11e5-a46b-4437e6b12281
          - name: CONSUL_BOOTSTRAP_EXPECT
            value: 3
          - name: CONSUL_ENCRYPT
            value: X58Yxgqiz/stKlFZBl0eFg==
          - name: CONSUL_RETRY_JOIN
            value: consul-vault.default.svc.cluster.local
        ports:
        - name: server
          containerPort: 8300
          protocol: TCP
        - name: serf-lan
          containerPort: 8301
          protocol: TCP
        - name: serf-lan-udp
          containerPort: 8301
          protocol: UDP
        - name: serf-wan
          containerPort: 8302
          protocol: TCP
        - name: serf-wan-udp
          containerPort: 8302
          protocol: UDP
        - name: rpc
          containerPort: 8400
          protocol: TCP
        - name: http
          containerPort: 8500
          protocol: TCP
        - name: dns
          containerPort: 8600
          protocol: TCP
        - name: dns-udp
          containerPort: 8600
          protocol: UDP
        restartStrategy: always
        volumeMounts:
        - name: data
          mountPath: /data
      - name: vault
        image: dysinger/vault:0.3.1
        ports:
        - name: vault
          containerPort: 8200
          protocol: TCP
        restartStrategy: always
      volumes:
      - name: data
        emptyDir: {}
