apiVersion: v1
kind: Service
metadata:
  name: consul-vault
  labels:
    app: consul-vault
spec:
  ports:
  - name: vault
    port: 8200
    protocol: TCP
    targetPort: vault
  - name: server
    port: 8300
    protocol: TCP
    targetPort: server
  - name: serf-lan
    port: 8301
    protocol: TCP
    targetPort: serf-lan
  - name: serf-lan-udp
    port: 8301
    protocol: UDP
    targetPort: serf-lan-udp
  - name: serf-wan
    port: 8302
    protocol: TCP
    targetPort: serf-wan
  - name: serf-wan-udp
    port: 8302
    protocol: UDP
    targetPort: serf-wan-udp
  - name: rpc
    port: 8400
    protocol: TCP
    targetPort: rpc
  - name: http
    port: 8500
    protocol: TCP
    targetPort: http
  - name: dns
    port: 8600
    protocol: TCP
    targetPort: dns
  - name: dns-udp
    port: 8600
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: consul-vault
