apiVersion: v1
kind: ReplicationController
metadata:
  name: sig-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sig-service
    spec:
      containers:
      - name: rdr2tls
        image: dysinger/rdr2tls:0.1.1
        command:
        - rdr2tls
        - --port
        - "8080"
        ports:
        - name: http
          containerPort: 8080
        restartStrategy: always
      - name: sig-service
        image: dysinger/sig-service:0.0.1
        command:
        - sig-service
        - Testing
        - --port
        - "8443"
        ports:
        - name: https
          containerPort: 8443
        restartStrategy: always
        volumeMounts:
        - name: secret
          mountPath: /opt/sig-service/secret
      volumes:
      - name: secret
        secret:
          secretName: sig-service
