apiVersion: v1
kind: Service
metadata:
  name: sig-service
  labels:
    app: sig-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: sig-service
  type: LoadBalancer
