# Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  ports:
  - name: server
    port: 8300
    protocol: TCP
    targetPort: server
  - name: serf-lan
    port: 8301
    protocol: TCP
    targetPort: serf-lan
  - name: serf-lan-udp
    port: 8301
    protocol: UDP
    targetPort: serf-lan-udp
  - name: serf-wan
    port: 8302
    protocol: TCP
    targetPort: serf-wan
  - name: serf-wan-udp
    port: 8302
    protocol: UDP
    targetPort: serf-wan-udp
  - name: rpc
    port: 8400
    protocol: TCP
    targetPort: rpc
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  - name: dns
    port: 8600
    protocol: TCP
    targetPort: dns
  - name: dns-udp
    port: 8600
    protocol: UDP
    targetPort: dns-udp
  selector:
    app: consul
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: consul
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: dysinger/consul:0.5.2
        ports:
        - name: server
          containerPort: 8300
          protocol: TCP
        - name: serf-lan
          containerPort: 8301
          protocol: TCP
        - name: serf-lan-udp
          containerPort: 8301
          protocol: UDP
        - name: serf-wan
          containerPort: 8302
          protocol: TCP
        - name: serf-wan-udp
          containerPort: 8302
          protocol: UDP
        - name: rpc
          containerPort: 8400
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: dns
          containerPort: 8600
          protocol: TCP
        - name: dns-udp
          containerPort: 8600
          protocol: UDP
        restartStrategy: always
        volumeMounts:
        - name: data
          mountPath: /data
        - name: secret
          mountPath: /secret
      volumes:
      - name: data
        emptyDir: {}
      - name: secret
        secret:
          secretName: consul
---
apiVersion: v1
kind: Secret
metadata:
  name: consul
type: Opaque
data:
  consul.json: |
    << base64 encoded consul.json goes here >>
  ca.cert: |
    << base64 encoded pem file goes here >>
  consul.cert: |
    << base64 encoded pem file goes here >>
  consul.key: |
    << base64 encoded pem file goes here >>
