Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Insert copyright statement here
  pull-minutes: 30
  repo-url: git@github.com:commercialhaskell/sig-archive.git
  repo-path: /opt/sig-service/sig-archive
  repo-branch: master
  repo-key-path: /opt/sig-service/secret/github.pem

Development:
  pull-minutes: 1
  repo-branch: test
  <<: *defaults

Testing:
# approot: "https://sig-test.commercialhaskell.org"
  pull-minutes: 5
  repo-branch: test
  <<: *defaults

Staging:
# approot: "https://sig-staging.commercialhaskell.org"
  pull-minutes: 10
  repo-branch: test
  <<: *defaults

Production:
# approot: "https://sig.commercialhaskell.org"
  <<: *defaults
