Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Insert copyright statement here
  pull-minutes: 30
  repo-url: git@github.com:commercialhaskell/sig-archive.git
  repo-path: sig-archive
  cache-dir: /tmp/sig-archive-cache

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
