Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Insert copyright statement here
  pull-minutes: 30
  repo-url: git@github.com:commercialhaskell/sig-archive.git
  repo-path: sig-archive
  repo-branch: master
  cache-dir: /opt/sig-service/sig-archive

Development:
  pull-minutes: 1
  repo-branch: test
  <<: *defaults

Testing:
  pull-minutes: 3
  repo-branch: test
  <<: *defaults

Staging:
  repo-branch: test
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
